### ISSUE TITLE
运行main.py报错

### ISSUE THREAD

**Issue by Dlian-Zero** [yuweiping/jd_seckill_2024#2]
Traceback (most recent call last):
  File "main.py", line 29, in <module>
    jdSeckill = JdSeckill()
  File "/mnt/jd_seckill_2024/jd_seckill.py", line 23, in __init__
    self.spider_session = SpiderSession()
  File "/mnt/jd_seckill_2024/SpiderSession.py", line 33, in __init__
    self.init_param()
  File "/mnt/jd_seckill_2024/SpiderSession.py", line 42, in init_param
    self.client = result['client']
KeyError: 'client'

**Comment by Dlian-Zero** [comment]
运行环境是docker部署的Ubuntu

**Comment by Chris-JLin** [comment]
一样的问题，请问怎么解决

**Comment by CNRocker** [comment]
可能是python版本的问题，我用Python 3.10.2，不报这个错，但是sign失败，求解

**Comment by yuweiping** [comment]
> 可能是python版本的问题，我用Python 3.10.2，不报这个错，但是sign失败，求解

我用的3.11.7

**Comment by awordx** [comment]
是不是api_jd_url填错了，result没获取到信息
